"""Hyperparameters for ViT on CASIA log-mel (64×160)."""
from __future__ import annotations

N_MELS = 64
MAX_TIME_FRAMES = 160

PATCH_MEL = 8
PATCH_TIME = 10
PATCH_DIM = PATCH_MEL * PATCH_TIME  # 80
N_MEL_PATCHES = N_MELS // PATCH_MEL  # 8
N_TIME_PATCHES = MAX_TIME_FRAMES // PATCH_TIME  # 16
NUM_PATCHES = N_MEL_PATCHES * N_TIME_PATCHES  # 128

PROJECTION_DIM = 64
NUM_HEADS = 4
NUM_LAYERS = 3
DROPOUT = 0.1

# Block MLP: 64 → 256 → 64
VIT_MLP_HIDDEN = 256

# Flatten head: 8192 → 256 → 6
VIT_HEAD_UNITS: tuple[int, ...] = (256,)

# Legacy aliases (deprecated)
TF_SER_MLP_HIDDEN = VIT_MLP_HIDDEN
TF_SER_HEAD_UNITS = VIT_HEAD_UNITS
TF_SER_HEAD_DROPOUT = 0.3
